{{- if and .Values.pgbackrest.enabled .Values.pgbackrest.s3.enabled .Values.pgbackrest.s3.tls.enabled }}
{{- $ns := default .Release.Namespace .Values.pgbackrest.s3.tls.caSecret.namespace }}
{{- $name := .Values.pgbackrest.s3.tls.caSecret.name }}
{{- $key := default "tls.crt" .Values.pgbackrest.s3.tls.caSecret.key }}
{{- $src := (lookup "v1" "Secret" $ns $name) }}
{{- if not $src }}
{{- fail (printf "MinIO CA Secret '%s' not found in namespace '%s'. Set pgbackrest.s3.tls.caSecret.{name,namespace}." $name $ns) }}
{{- end }}
{{- if not (has $key (keys $src.data)) }}
{{- fail (printf "Key '%s' not found in Secret '%s/%s'." $key $ns $name) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}-minio-ca
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
  annotations:
    # Mirror of external MinIO CA into release namespace for mounting
    helm.sh/resource-policy: keep
type: Opaque
data:
  # Copy only CA cert; value already base64-encoded in source Secret
  tls.crt: {{ index $src.data $key }}
{{- end }}
