apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "postgresql.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgresql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgresql.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
        {{- if and .Values.pgbackrest.enabled .Values.pgbackrest.s3.enabled .Values.pgbackrest.s3.tls.enabled }}
        fsGroup: 1001
        {{- end }}
      
      {{- if and .Values.pgbackrest.enabled .Values.pgbackrest.s3.enabled .Values.pgbackrest.s3.tls.enabled }}
      # Install custom MinIO CA into OS trust store (Bitnami-style, PodSecurity-restricted compliant)
      initContainers:
      - name: minio-ca-init
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        command:
        - /bin/bash
        - -c
        - |
          set -e
          # Copy MinIO CA cert from mounted Secret into OS trust store
          # pgBackRest will use /etc/ssl/certs to verify HTTPS connections
          cp /usr/local/share/ca-certificates/minio/tls.crt /etc/ssl/certs/minio-ca.crt
          echo "CA certificate installed at /etc/ssl/certs/minio-ca.crt"
        volumeMounts:
        # Mount CA Secret from mirrored Secret in release namespace
        - name: minio-ca
          mountPath: /usr/local/share/ca-certificates/minio
          readOnly: true
        # Writable cert store shared with main container (owned by fsGroup 1001)
        - name: ssl-certs
          mountPath: /etc/ssl/certs
      {{- end }}

      containers:
      
      - name: postgresql
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        args:
        - "-c"
        - "config_file=/etc/postgresql/postgresql.conf"

        ports:
        - name: postgresql
          containerPort: 5432
          protocol: TCP
        
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "postgresql.fullname" . }}
              key: username
        
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "postgresql.fullname" . }}
              key: password
        
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.database | quote }}
        
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        
        - name: POSTGRES_INITDB_ARGS
          value: "--encoding=UTF8"
        
        - name: POSTGRES_CONFIG_FILE
          value: /etc/postgresql/postgresql.conf
        
        {{- if and .Values.pgbackrest.enabled .Values.pgbackrest.s3.enabled }}
        - name: PGBACKREST_REPO1_S3_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "postgresql.fullname" . }}-pgbackrest-s3
              key: PGBACKREST_REPO1_S3_KEY
        - name: PGBACKREST_REPO1_S3_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "postgresql.fullname" . }}-pgbackrest-s3
              key: PGBACKREST_REPO1_S3_KEY_SECRET
        {{- end }}
        
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U {{ .Values.postgresql.username }} -d {{ .Values.postgresql.database }} -h localhost
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U {{ .Values.postgresql.username }} -d {{ .Values.postgresql.database }} -h localhost
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        
        volumeMounts:
        - name: postgresql-storage
          mountPath: {{ .Values.persistence.mountPath }}
        - name: postgresql-config
          mountPath: /etc/postgresql
          readOnly: true
        {{- if and .Values.pgbackrest.enabled .Values.pgbackrest.s3.enabled .Values.pgbackrest.s3.tls.enabled }}
        # Make CA available and use the shared certs path
        - name: minio-ca
          mountPath: /usr/local/share/ca-certificates/minio
          readOnly: true
        - name: ssl-certs
          mountPath: /etc/ssl/certs
        {{- end }}
        {{- if .Values.pgbackrest.enabled }}
        - name: pgbackrest-config
          mountPath: /etc/pgbackrest
          readOnly: true
        - name: pgbackrest-log
          mountPath: /var/log/pgbackrest
        {{- end }}
      
      volumes:
      - name: postgresql-config
        configMap:
          name: {{ include "postgresql.fullname" . }}-config
      {{- if and .Values.pgbackrest.enabled .Values.pgbackrest.s3.enabled .Values.pgbackrest.s3.tls.enabled }}
      # Secret mirrored from external MinIO namespace
      - name: minio-ca
        secret:
          secretName: {{ include "postgresql.fullname" . }}-minio-ca
      # Writable cert store shared with initContainer
      - name: ssl-certs
        emptyDir: {}
      {{- end }}
      {{- if .Values.pgbackrest.enabled }}
      - name: pgbackrest-config
        configMap:
          name: {{ include "postgresql.fullname" . }}-pgbackrest-config
      - name: pgbackrest-log
        emptyDir: {}
      {{- end }}
      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  
  volumeClaimTemplates:
  - metadata:
      name: postgresql-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.persistence.storageClass }}
      storageClassName: {{ .Values.persistence.storageClass }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}