{{- if and .Values.pgbackrest.enabled .Values.pgbackrest.hooks.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "postgresql.fullname" . }}-hooks
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-20"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "postgresql.fullname" . }}-hooks
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-20"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: 
      - {{ include "postgresql.fullname" . }}-archive-config
    verbs: ["get", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    resourceNames: 
      - {{ include "postgresql.fullname" . }}
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "postgresql.fullname" . }}-hooks
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-15"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "postgresql.fullname" . }}-hooks
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "postgresql.fullname" . }}-hooks
{{- end }}
