{{- if and .Values.backup.enabled .Values.backup.s3.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "postgresql.fullname" . }}-backup
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
{{- end }}
