{{- if and .Values.pgbackrest.enabled .Values.pgbackrest.s3.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}-pgbackrest-s3
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  # pgBackRest-native environment variables for S3 credentials
  PGBACKREST_REPO1_S3_KEY: {{ .Values.pgbackrest.s3.credentials.accessKeyId | quote }}
  PGBACKREST_REPO1_S3_KEY_SECRET: {{ .Values.pgbackrest.s3.credentials.secretAccessKey | quote }}
  # Helpful pgBackRest variables for bucket and repo path
  PGBACKREST_REPO1_S3_BUCKET: {{ .Values.pgbackrest.s3.bucket | quote }}
  PGBACKREST_REPO1_PATH: {{ .Values.pgbackrest.s3.path | quote }}
{{- end }}
